lib/broadway/producer.ex
test/broadway/producer_test.exs

The producer should return `:ok` when the wrapped module doesn't define one.

Add default terminate/2 returning :ok to producer

---

lib/broadway.ex

Adds `alias` so that the `Message` function can be used and the example comment will compile.

Fix example comment

---

lib/broadway/producer.ex

Let's just look at the head. If the head is correct,
it is very likely that the rest is correct too.

Avoid traversing all messages for validation

---

README.md
lib/broadway.ex
lib/broadway/batch_info.ex
lib/broadway/batcher.ex
lib/broadway/consumer.ex
lib/broadway/message.ex
lib/broadway/processor.ex
lib/broadway/server.ex
test/broadway/batcher_test.exs
test/broadway/processor_test.exs
test/broadway_test.exs

Closes #27. The documentation should probably show examples of using the new process key. However we can do this later after implementing multiple processors. The current implementation is similar to the producers which allows only one key, so the first arg of `handle_message/3` is there just to define the "final" API.

Revise configuration API

---

lib/broadway.ex
lib/broadway/batch_info.ex
lib/broadway/batcher.ex
lib/broadway/consumer.ex
lib/broadway/message.ex
lib/broadway/server.ex
test/broadway/batcher_test.exs
test/broadway_test.exs

Because we may have mutiple partitions along the way,
it is probably best to distance ourselves from the
"partition" name. Instead, `batch_key` is used, as it
is one of the factor for specifying a batch beyond the
batch_size and batch_timeout.
To avoid  confusion, batcher_key in `%BatchInfo{}` was
rename to batcher (to mirror `put_batcher`) and `batcher_pid`
was removed for now.

 Rename batcher_key to batcher and partition to batch_key

---

lib/broadway/producer.ex
lib/broadway/terminator.ex
test/broadway/producer_test.exs
test/broadway_test.exs

This is required for active producers like `BroadwayRabbitmq.Producer`

Allow producers to be canceled for shutdown

---

lib/broadway.ex

I've been spending a lot of time reading these docs recently, so here are a couple of fixes for typos I noticed 😄
Thanks for all your work on this library!

Fixed a handful of typos

---

lib/broadway/server.ex
test/broadway_test.exs

As mentioned in https://github.com/plataformatec/broadway/pull/73#issuecomment-487303696.
I counted 11 processes to be renamed in my local app and verified I got them all locally. Not sure if there are any others I may have missed.
```
MyBroadway.BatcherConsumerSupervisor_print
MyBroadway.BatcherPartitionSupervisor
MyBroadway.Batcher_print
MyBroadway.ConsumerSupervisor_print
MyBroadway.Consumer_print_1
MyBroadway.ProcessorSupervisor
MyBroadway.Processor_default_1
MyBroadway.ProducerSupervisor
MyBroadway.Producer_sqs_1
MyBroadway.Supervisor
MyBroadway.Terminator
```

Append .Broadway to module prefixes to avoid potential naming conflicts.

---

lib/broadway/batcher.ex

While reviewing the code I noticed that the the `split_counting` clauses had
different arities. There's also a guard on the first one which made it
suspicious. I thought that there might be a case when this would lead to
a `FunctionClauseError`.
It turns out that the guard will always return with true because `batch_size`
must be a positive number and `split_counting` is not really recursive. It
always passes back control to `handle_events_per_batch_key` which will let
`deliver_or_update_batch` handle the `count = 0` case.
This also means that there is some room for optimisation here because currently
we're calling `put_batch` after each event even if there are more events with
the same batch key and there is room in the batch for more events.
I haven't tested the performance benefits. I …

Optimise batcher for subsequent events with the same batch key

---

lib/broadway.ex
lib/broadway/batcher.ex
lib/broadway/message.ex
test/broadway_test.exs

Closes #92.
Worth mentioning that for people using default batch size of 100 the following works:
```elixir
ref = Broadway.test_messages(broadway, [1, 2, 3, 4])
assert_receive {:ack, ^ref, [%{data: 1}, %{data: 2}, %{data: 3}, %{data: 4}], []}
```
so it's not that people would necessarily get a lot more acknowledgments, we only got them (which required us to tweak our tests) because we had low batch size in tests.

Add `:batch_mode` and default to `:flush` for test messages

---

lib/broadway/acknowledger.ex
lib/broadway/caller_acknowledger.ex
lib/broadway/message.ex
test/broadway_test.exs

Some notes:
* I didn't add the `configure/3` callback to `NoopAcknowledger` because I think it's good if it raises if you call `configure_ack/3` after calling `ack_immediately`. Do we want to implement it and raise an even better message?
* Do we need to support a list of messages in `configure_ack/3`?

Add Broadway.Message.configure_ack/3

---

lib/broadway.ex
lib/broadway/producer.ex
lib/broadway/server.ex
test/broadway/producer_test.exs
test/broadway_test.exs

This PR injects a `:broadway_topology_index` option in the producer-specific options, but only if those options are a keyword list. I picked the first name I could think of, but not sure it's a great name so very open to renaming it :)

Inject topology index when starting producers

---

lib/broadway/message.ex

With `:atom`, Dialyzer expects an atom named `:atom` as a key!

Proper atom type in Message's Typespec

---

mix.exs

Broadway has a few more public modules now, so I thought it might be helpful to add some grouping in the docs.

Add doc groups for modules

---

guides/examples/Google Cloud PubSub.md

* Normalizes tenses in the Getting Started intro
* Adds a note about waiting for a new project's organization policy in the event of an error when creating the test topic
* Completes the explanation of the IAM binding, and links to the available pubsub roles
* Fixes miscellaneous typos

Improve Google Cloud Pub/Sub Guide

---

lib/broadway/producer.ex
test/broadway_test.exs

We need this for `broadway_sqs` and `broadway_kafka` to make sure we don't fetch any message after start draining.

Return new state on prepare_for_draining

---

lib/broadway.ex

Commit 8f101fa637020dc85214e058007e8c601a3cb868 changed the configuration to use a singular `:producer` rather than multiple `:producers`, so this updates the docs to match.

update producer docs

---

lib/broadway.ex
test/broadway_test.exs

BroadwayRabbitMQ.Producer allows appending certain metadata fields
to the message. This comes useful when we want to retrieve additional
information that is exposed by RabbitMQ, but not part of the message
body.
If our producer's `handle_message` function relies on `:metadata`, currently
we cannot test it with `test_messages`.

Allow passing `:metadata` field to `test_messages`

---

lib/broadway.ex
lib/broadway/producer.ex
lib/broadway/rate_limiter.ex
lib/broadway/server.ex
test/broadway/producer_test.exs
test/broadway_test.exs

Initial work on rate limiting producers. I think that this is the right direction, butI might be wrong so let me know :) Some questions:
* we should probably limit the size of the buffer where we store messages. Should we have `:buffer_keep` and `:buffer_size` like GenStage has?
* right now, the rate limiting is per producer. At work, we need rate limiting per pipeline, that is, the total number of messages consumed needs to be under a certain rate. A solution can be to just have each producer have a rate limit of `total_rate_limit / number_of_producers` per second. This practically works but might not be optimal because if a producer can produce a lot while another producer is slow, the fast producer will be penalized by its own rate limiting instead of sharing the rate limiting and …

Add support for rate limiting producers

---

lib/broadway/consumer.ex

When reporting failed messages the consumer uses the `size` from `BatchInfo` instead of the number of failed messages.
This causes a runtime error when you implement `handle_failed/2` callback and only some messages in the batch fails.

Fix handle failed messages

---

lib/broadway.ex

Fix typo in docs

---

README.md

Just update last release on readme https://github.com/plataformatec/broadway/releases/tag/v0.5.0

Use last release 0.5.0 on README [ci skip]

---

lib/broadway.ex
lib/broadway/processor.ex
test/broadway_test.exs

Creating a new PR to implement individual processor events per message (as was discussed in #152).

Added individual processor message telemetry events

---

lib/broadway.ex
lib/broadway/rate_limiter.ex
test/broadway_test.exs

We have `Broadway.update_rate_limiting/2` so it might be nice to have a way to get the current rate limiting information out of a Broadway pipeline. In our system at work, we'd use this mostly during testing to assert that the rate limiting of our pipelines is right, but I can imagine this being possibly used to make dynamic decisions about the rate limiting. I'm not 100% convinced about this since it has the obvious race condition of getting you the rate limiting info at a given time with that info possibly changing soon after, but since it's so little code, I thought I'd just send a PR and kickstart the discussion here. Thoughts?

Add Broadway.get_rate_limiting/1

---

lib/broadway.ex

This makes it clear that there is a default `child_spec/1`
impelementation generated when invoking `use Broadway`, and that if
users would like to change that spec they can override that function or
start the process with an explicitly passed child spec.

Improve documentation around child spec configuration

---

lib/broadway.ex

This documentation is really great, but with its size, it gets harder to navigate.
So, I would like to suggest adding some links to the sections which are mentioned throughout the documentation.
Please, let me know what you think and if there is a better way to generate the links.
This is an example of how it would look like:

Add links to the mentioned sections

---

lib/broadway.ex

This makes Broadway similar to many OTP behaviours. It's nice cause in my pipelines I can say that `start_link` returns `t:Broadway.on_start/0`.

Add @spec to Broadway.start_link/2

---

guides/examples/RabbitMQ.md

Ran into a little incompatibility bump while kicking the tires on Broadway. Perhaps there are API changes here that also need updated? I was able to get a producer / consumer working with the provided code, fwiw. 
Thanks for this library!

Docs: specify the latest release of broadway_rabbitmq

---

lib/broadway.ex
lib/broadway/processor.ex
test/broadway_test.exs

This callback will allow preparing messages before sending to
handle_message.
Related to issue: https://github.com/dashbitco/broadway/issues/172

Add prepare messages callback

---

guides/examples/Amazon SQS.md
guides/examples/Apache Kafka.md
guides/examples/Google Cloud PubSub.md
guides/examples/RabbitMQ.md
lib/broadway.ex

- Add notes on how producer concurrency may affect internal queueing and
on how messages are delivered to concurrent batchers
- Link from each producer-specific guide to those sections
- Update RabbitMQ example to use one producer, as in the
BroadwayRabbitMQ docs

Clarify effect of some concurrency settings

---

lib/broadway/topology.ex
lib/broadway/topology/producer_stage.ex
lib/broadway/topology/rate_limiter.ex

Switching the counter implementation in RateLimiter from ETS to atomics given that it looks like OTP 21.3+ is a requirement for Broadway (https://github.com/dashbitco/broadway/blob/master/lib/broadway/topology.ex#L40-L44).
I also opted for atomics as opposed to counters given that there are no `{sub,add}_get` BIFs in OTP for counters and I did not want to introduce a read after write issue with `RateLimiter.rate_limit/2` function.
Thanks in advance for any feedback!

RateLimiter ETS to atomics

---

lib/broadway.ex
lib/broadway/topology.ex
test/broadway_test.exs

I am currently working on the PromEx Broadway plugin (https://github.com/akoutmos/prom_ex/pull/39) and would like to incorporate some of the configuration details into the Broadway Grafana dashboard. Thoughts on surfacing the config from the Topology module after the supervisor is started?
If you are okay with this approach I will go through and add the necessary documentation to the telemetry events. Thanks in advance!

Added supervisor init telemetry event

---

lib/broadway.ex
test/broadway_test.exs

In our app we redefined mentioned functions to enable using different Acknowledgers. I think that this is a very small change but can be actually useful for others. I do think CallerAcknowledger is totally good enough for testing only, but we do have a customer acknowledger that we use for :dev level dirty debugging.
I decided to commit only changes needed to validate and demonstrate the idea. If I will get any positive feedback on this PR I will write the necessary documentation and tests.

Added proposed ack configuration for Broadway.test_message/3 and test_batch/3

---

lib/broadway/acknowledger.ex
test/broadway/acknowledger_test.exs

"Erlang errors" in `Broadway` callbacks were being reported as exits in the `Logger` metadata.
i.e.:
```elixir
:erlang.error(:something)
Logger.error("...", crash_reason: {:something, __STACKTRACE__})
Logger.error("...", crash_reason: {%ErlangError{original: :something}, __STACKTRACE__})
```
Questions:
- want me to update `CHANGELOG.md` for this?
- is there a better place for the tests?

Fix Logger crash_reason for Erlang errors

---

lib/broadway.ex
lib/broadway/topology.ex
test/broadway_test.exs

Also change the value to use a struct. The reason for these changes is
to make easier to detect a Broadway pipeline config from
`:persistent_term`.

Change `:persistent_term` key use namespace

---

lib/broadway.ex
lib/broadway/topology.ex
lib/broadway/topology/batch_processor_stage.ex
lib/broadway/topology/batcher_stage.ex
lib/broadway/topology/processor_stage.ex
test/broadway_test.exs

This PR adds these two fields in order to better inspect which stage and Broadway is emitting the event.
Discussion from: https://github.com/dashbitco/broadway_dashboard/pull/2#issuecomment-850603896

Add `index` and `topology_name` to telemetry event metadata

---

lib/broadway/topology/terminator.ex
test/broadway_test.exs

Playing with this locally, realized I missed a few call sites. These are the last ones outside of test where we are using `Process.whereis` as opposed to `GenServer.whereis`

Use GenServer.whereis() in remaining places to support via tuples

---

lib/broadway.ex
lib/broadway/topology.ex
lib/broadway/topology/batcher_stage.ex
lib/broadway/topology/processor_stage.ex
test/broadway_test.exs

This commit adds `batcher_key` and `processor_key` to events that don't
have it yet. This attribute is the same from the name of the processors
or the batchers that goes in the Broadway configuration.
The same keys are present now in the topology description. This can help
users to match telemetry events with the topology.

Add "keys" to telemetry events and topology/1

---

lib/broadway/topology.ex
lib/broadway/topology/batch_processor_stage.ex
lib/broadway/topology/batcher_stage.ex
lib/broadway/topology/processor_stage.ex
test/broadway_test.exs

feature #245: Adding context to telemetry event metadata.

---

lib/broadway.ex

This metadata field was formatted differently and after docs were produced it sticks like sore eye. I think it would be beneficial to just keep it consistent.

Changed telemetry docs so they are consistent.

---

guides/examples/google-cloud-pubsub.md

it seems that `brew cask install` doesn't work anymore.

Update command to install google-cloud-sdk

---

lib/broadway/batch_info.ex
lib/broadway/topology/batcher_stage.ex
test/broadway_test.exs

Adding an is_full field to %BatchInfo{} that indicates whether batch is full (:size == batch_size), whether it will be consumed after timeout or not. Discussed in  https://github.com/dashbitco/broadway/issues/253.

Add trigger field to BatchInfo

---

CHANGELOG.md
lib/broadway.ex
lib/broadway/topology.ex
test/broadway_test.exs

Since we changed to use `:telemetry.span/3`, the events have now
a different name for the system time field. This change normalizes the
events following the "span" convention.

Fix telemetry event measurements names and docs

---

test/broadway_test.exs

Try to fix an intermittent test by increasing the timeout of two
specific "assert_receive" assertions.

Increase timeout so the CI won't fail easily

---

lib/broadway/topology/processor_stage.ex
test/broadway_test.exs

This fixes a bug that was introduced in [this commit](https://github.com/dashbitco/broadway/commit/95d6aeaa9512d7447b8cd0f1e4d50c382dbbf82d). Specifically if `handle_message/3` calls `Broadway.Message.failed/2`, telemetry events do not reflect the failure.

Ensuring telemetry events are correct when handle_message/3 calls Message.failed/2.

---

lib/broadway/topology/subscriber.ex

As discussed in #269, the shuffling cannot really balancing the loading across consumers.

Remove unnecessary shuffling in Subscriber.init/1

---

guides/internals/architecture.md

The name change on the 1.0.0 release, from `Consumer` to `BatchProcessor`, wasn't applied in the architecture documentation.
PS: I'm assuming that's the case because I haven't seen that term in the illustration and also because this change happened for the metrics' names.

Fix outdated name for BatchProcessor in architecture guide

---

lib/broadway.ex

Just fixing the function argument name which was supposed to be `repo`.

Fix documentation about testing with Ecto

---

lib/broadway.ex
lib/broadway/topology.ex
test/broadway_test.exs

It seems like this callback was accidentally generated inside the module calling `use Broadway` instead of being part of the Broadway behaviour.
This callback was originally introduced in https://github.com/dashbitco/broadway/pull/239.

Move c:process_name/2 to the Broadway behaviour

---

lib/broadway/topology/producer_stage.ex

The spec seems to be missing an argument.

Fix ProducerStage start_link spec

---

guides/examples/apache-kafka.md

Clarified that it is always possible that duplicate messages may be
received by Kafka consumers.
Also two minor typos.

Clarification on consuming duplicate messages

---

lib/broadway.ex

`Broadway.Message.put_batcher/2` requires `message` as the first argument.

Add `message` argument to the batcher example

---

lib/broadway.ex

It fixes the next telemetry warning:
```
Function passed as a handler with ID {App.BroadwayEctoSandbox, App.Repo} is local function.
This mean that it is either anonymous function or capture of function without module specified. That may cause performance penalty when calling such handler. For more details see note in `telemetry:attach/4` documentation.
https://hexdocs.pm/telemetry/telemetry.html#attach-4
```

fix: documentation example to configure BroadwayEctoSandbox

---

lib/broadway.ex

There is a bit of misleading documentation in the telemetry section, where the `[:broadway, :topology, :init]` event is said to receive `%{supervision: pid, config: keyword}` as metadata.
A test at <https://github.com/dashbitco/broadway/blob/v1.0.3/test/broadway_test.exs#L254> in fact asserts that the correct key is `:supervisor_pid`.
Here is the fix to the documentation.

Update documentation about the topology init event

---

guides/examples/introduction.md

[off_broadway_amqp10](https://github.com/highmobility/off_broadway_amqp10) is a connector that we are using with [Azure ServiceBus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-overview).

add link to off_broadway_amqp10

---

lib/broadway/message.ex

At work we use `failed/2` with tuples to facilitate pattern matching within the `handle_failed/2` callback such as:
```elixir
def dispatch(message) do
case dispatch_email(message) do
...
{:error, reason} -> 
Message.failed(message, {:email_dispatch, reason})
end
end
```
```elixir
def handle_failed(messages, context) do
Enum.map(messages, fn
...
%Message{status: {:failed, {:email_dispatch, reason}}} = message ->
Logger.error(" ... ")
Message.configure_ack(message, on_failure: :noop)
end)
end
```
In our tests we make use of [Hammox](https://hexdocs.pm/hammox/Hammox.html) to mock functions such as `dispatch`, but such tests fail with a `Hammox.TypeMatchError` because the `Broadway.Message` typespec requires the failed reason to be a binary.
So I propose the typespec be updated to allow any …

Change the typespec of Broadway.Message.failed/2

---

lib/broadway/topology/batch_processor_stage.ex

Without this, the error is:
```
10:10:34.307 [error] ** (FunctionClauseError) no function clause matching in Broadway.Topology.BatchProcessorStage.split_by_status/4
(broadway 1.0.6) lib/broadway/topology/batch_processor_stage.ex:118: Broadway.Topology.BatchProcessorStage.split_by_status(:ok, [], [], 0)
(broadway 1.0.6) lib/broadway/topology/batch_processor_stage.ex:104: Broadway.Topology.BatchProcessorStage.handle_batch/4
(broadway 1.0.6) lib/broadway/topology/batch_processor_stage.ex:58: anonymous fn/5 in Broadway.Topology.BatchProcessorStage.handle_events/3
(telemetry 1.2.1) /Users/andrea/Library/Caches/mix/installs/elixir-1.14.2-erts-13.0.4/a2f9ee168726c26df78129abc19240bd/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
(gen_stage 1.2.1) lib/gen_stage.ex:2578: …
```

Improve error on bad handle_batch/4 return

---

guides/examples/introduction.md

Hi, I've written a Splunk producer for Broadway and figured it may be useful to link to it from the official docs.

docs: add link to off_broadway_splunk

---

lib/broadway.ex

Noticed the options seem to be swapped for `test_message` and `test_batch`:
- `test_message` docs shows `batch_mode` when it doesn't have any effect 
- `test_batch` docs don't show `batch_mode` when it is actually applicable

docs: fix test_message and test_batch options

---

lib/broadway.ex

This really confused me! I couldn't figure out why, no matter what I did with `min_demand` and `max_demand`, I would always get a single message in `c:prepare_messages/2`. I'm using the `RabbitMQ` producer. I asked [on the Elixir Forum](https://elixirforum.com/t/help-with-tuning-data-flow-in-broadway-c-prepare-messages-2-question/61049/4). I think this explains it a little more clearly so the next person doesn't get confused like me :). Very open to rewording to make it even clearer.

Provide more clarity on the length of list in `c:prepare_messages/2`

---

lib/broadway.ex
lib/broadway/config_storage.ex
lib/broadway/config_storage/ets.ex
lib/broadway/config_storage/persistent_term.ex
lib/broadway/topology.ex
test/broadway/config_storage_test.exs

This PR adds in an ETS configuration storage option, for #342 .
Our use case has many dynamically-created Broadway servers (each with different non-static names). This results in global GC getting triggered. Although https://github.com/dashbitco/broadway/commit/fb69a7a291877f5d3ed5e593db25d442aff90b56 has some improvements, it is insufficient for our situation.
If we were to continue using persistent term using the above mentioned change, it will result in large buildup in the hash table over time. As time to update/store the term is proportional to hash table size, resulting in degrading storage speeds over time. In our case, the memory buildup over time may also be non-negligible. 
However, without the above change (where the persistent term is not cleaned up), it will result in the GC …

feat: refactor persistent term usage to behaviour

---

lib/broadway/topology.ex

Seems like `function_exported/2` doesn't return true as the module isn't loaded at runtime.

fix: ensure config storage is loaded

---

guides/examples/introduction.md

This PR adds a reference to [off_broadway_elasticsearch](https://github.com/jonlunsford/off_broadway_elasticsearch) and the related hexdodcs [Guide](https://hexdocs.pm/off_broadway_elasticsearch/) to `guides/examples/introduction.md`.

Add `off_broadway_elasticsearch`

---

lib/broadway.ex
lib/broadway/config_storage/persistent_term.ex
lib/broadway/producer.ex

edited some grammatical issues i read across
and an example in the documentation seemed up for being relabeled 
and when I ran "mix format", it removed an "unless"
and mix docs through an error on a callback's arity so I fixed that

Minor documentation edits and one `mix format` edit
