dashbitco/broadway

lib/broadway.ex
lib/broadway/server.ex
test/broadway_test.exs

Add Broadway.push_messages/2

---

lib/broadway.ex
lib/broadway/caller_acknowledger.ex
test/broadway_test.exs

Add Broadway.test_messages/2

---

guides/examples/Amazon SQS.md
lib/broadway.ex

Add SQS guide

---

guides/examples/RabbitMQ.md

* Remove declare options
* Note about non-existing queues

Update RabbitMQ guide

---

guides/examples/Amazon SQS.md
lib/broadway/message.ex

Add metadata field and update docs

---

guides/examples/RabbitMQ.md

The link was not working to me. I update it with the current link.

fix broken link

---

README.md

Thanks to @jeffgrunewald for the idea!

Explain the name and suggest off_broadway namespace

---

lib/broadway.ex

Just small changes in a few places I noticed while reading the docs.

Improve wording of main module docs

---

lib/broadway/batcher.ex

The various names used for `batch_key` in `Batcher` made it more difficult for me to follow the code. I believe batches used to be called partitions and that's where the different names are coming from.

Consistent variable naming in Batcher

---

guides/examples/Amazon SQS.md

Update `broadway_sqs` dependency version on guide.

Update BroadwaySQS version on guide

---

lib/broadway.ex
lib/broadway/dummy_producer.ex
lib/broadway/empty_producer.ex
test/broadway/dummy_producer_test.exs

Add Broadway.DummyProducer

---

README.md
guides/examples/Google Cloud PubSub.md
mix.exs

Add BroadwayCloudPubSub guide

---

lib/broadway/message.ex
lib/broadway/noop_acknowledger.ex
test/broadway_test.exs

Took a stab at this. I have very little idea of what I'm doing 🎊 
Closes #105.
\cc @josevalim @msaraiva

Add Broadway.Message.ack_immediately/1

---

CHANGELOG.md
lib/broadway.ex
lib/broadway/acknowledger.ex
lib/broadway/consumer.ex
lib/broadway/processor.ex
mix.exs
test/broadway_test.exs

As discussed with @josevalim, mostly in https://github.com/plataformatec/broadway_rabbitmq/pull/47.
Shoved commits everywhere, please squash before merging :)

Add the handle_failed/2 callback

---

guides/examples/Apache Kafka.md

Add kafka guide

---

guides/examples/Apache Kafka.md

Use `topic` instead of `queue` in the doc

Update Apache Kafka guide

---

guides/examples/Apache Kafka.md

Use topic instead of queue in callbacks section.

Kafka Guide Update

---

lib/broadway.ex
lib/broadway/batcher.ex
lib/broadway/consumer.ex
lib/broadway/processor.ex
lib/broadway/server.ex
mix.exs
mix.lock
test/broadway_test.exs

Add telemetry integration

---

guides/examples/Amazon SQS.md
lib/broadway.ex
lib/broadway/message.ex

Make minor improvements to documentation.

Improve documentation

---

guides/examples/Amazon SQS.md
guides/examples/Apache Kafka.md
guides/examples/RabbitMQ.md

Adds a new "Tuning the configuration" section

Update kafka guide

---

guides/examples/Google Cloud PubSub.md

Some of the text in the PubSub guide did not reflect https://github.com/dashbitco/broadway/issues/147

Fix reference to "stages" in PubSub guide

---

guides/internals/Architecture.md
lib/broadway.ex

Fixed some broken references, added `prepare_message/2` callback to architecture graph

Documentation improvements

---

lib/broadway/message.ex

Fix `failed/2` typespec

---

.github/workflows/ci.yml

The failure below is Unrelated™

Test on Elixir 1.11 on CI

---

lib/broadway/topology.ex
test/broadway_test.exs

I think validating the options twice is fine since Broadway's validation is pure and doesn't cast any of the options. What we have now is not a great alternative because you can screw up the options returned by that callback and the errors you get are obscure at best 😄 Thoughts?

Validate the prepare_for_start/2 callback

---

lib/broadway.ex

cc @josevalim, I think I got that right 😄

Add more docs about the :default batcher

---

lib/broadway.ex
lib/broadway/topology.ex
test/broadway_test.exs

It returns the description of each stage in a pipeline.

Add Broadway.topology/1

---

lib/broadway.ex

close https://github.com/dashbitco/broadway/issues/240

Update document to remove non-existent key

---

lib/broadway/topology/batch_processor_stage.ex
lib/broadway/topology/batcher_stage.ex
lib/broadway/topology/processor_stage.ex
mix.exs
mix.lock

Having the telemetry span function call in the code guarantees that conform to a standard with the version changes, making adoption more widely available and useful to the telemetry library authors.

feat: Replaces use of manual spans with telemetry:span/3

---

lib/broadway.ex
lib/broadway/options.ex
mix.exs
mix.lock

In particular, I added NimbleOptions validation to:
* `Broadway.test_message/3`
* `Broadway.test_batch/3`

Validate more options with nimble_options

---

lib/broadway.ex

fix: documentation example to configure producer

---

lib/broadway.ex
lib/broadway/caller_acknowledger.ex
lib/broadway/message.ex
lib/broadway/noop_acknowledger.ex
test/broadway_test.exs

Update broadway acknowlegers to have an `init/x` API

---

guides/examples/introduction.md

[Redis Stream](https://redis.io/docs/data-types/streams-tutorial/) connector for Broadway

Add link to off_broadway_redis_stream
